let win=0;
let count=0;
let ids=[];
let com=[];
let cards=[
    {
        shape:"black-parrot.jfif",
        id:"a",
        class:"card"
    },
    {
        shape:"black-parrot.jfif",
        id:"b",
        class:"card"
    },
    {
        shape:"blue-parrot.jfif",
        id:"c",
        class:"card"
    },
    {
        shape:"blue-parrot.jfif",
        id:"d",
        class:"card"
    },
    {
        shape:"green-parrot.jfif",
        id:"e",
        class:"card"
    },
    {
        shape:"green-parrot.jfif",
        id:"f",
        class:"card"
    },
    {
        shape:"rainbow-parrot.jfif",
        id:"g",
        class:"card"
    },
    {
        shape:"rainbow-parrot.jfif",
        id:"h",
        class:"card"
    },
    {
        shape:"white-parrot.jfif",
        id:"i",
        class:"card"
    },
    {
        shape:"white-parrot.jfif",
        id:"j",
        class:"card"
    },
    {
        shape:"pink-parrot.jfif",
        id:"k",
        class:"card"
    },
    {
        shape:"pink-parrot.jfif",
        id:"l",
        class:"card"
    },
    {
        shape:"black-parrot-2.jfif",
        id:"m",
        class:"card"
    },
    {
        shape:"black-parrot-2.jfif",
        id:"n",
        class:"card"
    },
    {
        shape:"blue-parrot-2.jfif",
        id:"o",
        class:"card"
    },
    {
        shape:"blue-parrot-2.jfif",
        id:"p",
        class:"card"
    },
    {
        shape:"green-parrot-2.jfif",
        id:"q",
        class:"card"
    },
    {
        shape:"green-parrot-2.jfif",
        id:"r",
        class:"card"
    },
    {
        shape:"pink-parrot-2.jfif",
        id:"s",
        class:"card"
    },
    {
        shape:"pink-parrot-2.jfif",
        id:"t",
        class:"card"
    },
    {
        shape:"rainbow-parrot-2.jfif",
        id:"u",
        class:"card"
    },
    {
        shape:"rainbow-parrot-2.jfif",
        id:"v",
        class:"card"
    },
    {
        shape:"white-parrot-2.jfif",
        id:"w",
        class:"card"
    },
    {
        shape:"white-parrot-2.jfif",
        id:"x",
        class:"card"
    },
    {
        shape:"crow.jfif",
        id:"y",
        class:"card"
    },
    {
        shape:"crow.jfif",
        id:"z",
        class:"card"
    },
    {
        shape:"casuary.jfif",
        id:"aa",
        class:"card"
    },
    {
        shape:"casuary.jfif",
        id:"ab",
        class:"card"
    }
];
let Cards_1=[
    {
        shape:"black-parrot.jfif",
        id:"a",
        class:"card"
    },
    {
        shape:"black-parrot.jfif",
        id:"b",
        class:"card"
    },
    {
        shape:"blue-parrot.jfif",
        id:"c",
        class:"card"
    },
    {
        shape:"blue-parrot.jfif",
        id:"d",
        class:"card"
    },
    {
        shape:"green-parrot.jfif",
        id:"e",
        class:"card"
    },
    {
        shape:"green-parrot.jfif",
        id:"f",
        class:"card"
    },
    {
        shape:"rainbow-parrot.jfif",
        id:"g",
        class:"card"
    },
    {
        shape:"rainbow-parrot.jfif",
        id:"h",
        class:"card"
    },
    {
        shape:"white-parrot.jfif",
        id:"i",
        class:"card"
    },
    {
        shape:"white-parrot.jfif",
        id:"j",
        class:"card"
    },
    {
        shape:"pink-parrot.jfif",
        id:"k",
        class:"card"
    },
    {
        shape:"pink-parrot.jfif",
        id:"l",
        class:"card"
    },
    {
        shape:"black-parrot-2.jfif",
        id:"m",
        class:"card"
    },
    {
        shape:"black-parrot-2.jfif",
        id:"n",
        class:"card"
    },
    {
        shape:"blue-parrot-2.jfif",
        id:"o",
        class:"card"
    },
    {
        shape:"blue-parrot-2.jfif",
        id:"p",
        class:"card"
    },
    {
        shape:"green-parrot-2.jfif",
        id:"q",
        class:"card"
    },
    {
        shape:"green-parrot-2.jfif",
        id:"r",
        class:"card"
    },
    {
        shape:"pink-parrot-2.jfif",
        id:"s",
        class:"card"
    },
    {
        shape:"pink-parrot-2.jfif",
        id:"t",
        class:"card"
    },
    {
        shape:"rainbow-parrot-2.jfif",
        id:"u",
        class:"card"
    },
    {
        shape:"rainbow-parrot-2.jfif",
        id:"v",
        class:"card"
    },
    {
        shape:"white-parrot-2.jfif",
        id:"w",
        class:"card"
    },
    {
        shape:"white-parrot-2.jfif",
        id:"x",
        class:"card"
    },
    {
        shape:"crow.jfif",
        id:"y",
        class:"card"
    },
    {
        shape:"crow.jfif",
        id:"z",
        class:"card"
    },
    {
        shape:"casuary.jfif",
        id:"aa",
        class:"card"
    },
    {
        shape:"casuary.jfif",
        id:"ab",
        class:"card"
    }
];;
let current='';
let score=0;
function low(){
    noback();
    cards.splice(4);
    while(cards[0].shape===cards[1].shape){
    cards.sort(function(){return 0.5 - Math.random()});}
    cards.forEach(display);
    document.getElementById('choices').innerHTML=`<buttom id='reset' onclick="location.reload()">reset</buttom>`;
    current='low';

}
function medium(){
    noback();
    cards.splice(6);
    while(cards[0].shape===cards[1].shape){
        cards.sort(function(){return 0.5 - Math.random()});}
    document.getElementById('stack').style.gridTemplateColumns='auto auto auto';
    cards.forEach(display);
    document.getElementById('choices').innerHTML=`<buttom id='reset' onclick="location.reload()">reset</buttom>`;
    current='medium';
}
function high(){
    noback();
    cards.splice(12);
    cards.sort(function(){return 0.5 - Math.random()});
    cards.forEach(display);
    document.getElementById('choices').innerHTML=`<buttom id='reset' onclick="location.reload()">reset</buttom>`;
    current='high';
}
function impossible(){
    console.log(Cards_1)
    console.log(cards)
    noback();
    cards.sort(function(){return 0.5 - Math.random()});
    document.getElementById('stack').style.gridTemplateColumns='auto auto auto auto auto auto auto';
    cards.forEach(display);
    document.getElementById('choices').innerHTML=`<buttom id='reset' onclick="location.reload()">reset</buttom>`;
    current='imposible';
}
function display(){
    const container = document.getElementById('stack');
        let html = ``;
        for(let i = 0; i < cards.length; i++) {
            if(cards[i].class=='solve'){html += `
            <button class=${cards[i].class} id="${cards[i].id}"></button>
            `;
        win+=1;
        }else{
            html += `
            <button onclick= select('${cards[i].id}','${cards[i].shape}') class=${cards[i].class} id="${cards[i].id}"></button>
            `;}         
        }
        count=0;
        if(win<cards.length){
        container.innerHTML=html;
    }else{

    cards=[
        {
            shape:"black-parrot.jfif",
            id:"a",
            class:"card"
        },
        {
            shape:"black-parrot.jfif",
            id:"b",
            class:"card"
        },
        {
            shape:"blue-parrot.jfif",
            id:"c",
            class:"card"
        },
        {
            shape:"blue-parrot.jfif",
            id:"d",
            class:"card"
        },
        {
            shape:"green-parrot.jfif",
            id:"e",
            class:"card"
        },
        {
            shape:"green-parrot.jfif",
            id:"f",
            class:"card"
        },
        {
            shape:"rainbow-parrot.jfif",
            id:"g",
            class:"card"
        },
        {
            shape:"rainbow-parrot.jfif",
            id:"h",
            class:"card"
        },
        {
            shape:"white-parrot.jfif",
            id:"i",
            class:"card"
        },
        {
            shape:"white-parrot.jfif",
            id:"j",
            class:"card"
        },
        {
            shape:"pink-parrot.jfif",
            id:"k",
            class:"card"
        },
        {
            shape:"pink-parrot.jfif",
            id:"l",
            class:"card"
        },
        {
            shape:"black-parrot-2.jfif",
            id:"m",
            class:"card"
        },
        {
            shape:"black-parrot-2.jfif",
            id:"n",
            class:"card"
        },
        {
            shape:"blue-parrot-2.jfif",
            id:"o",
            class:"card"
        },
        {
            shape:"blue-parrot-2.jfif",
            id:"p",
            class:"card"
        },
        {
            shape:"green-parrot-2.jfif",
            id:"q",
            class:"card"
        },
        {
            shape:"green-parrot-2.jfif",
            id:"r",
            class:"card"
        },
        {
            shape:"pink-parrot-2.jfif",
            id:"s",
            class:"card"
        },
        {
            shape:"pink-parrot-2.jfif",
            id:"t",
            class:"card"
        },
        {
            shape:"rainbow-parrot-2.jfif",
            id:"u",
            class:"card"
        },
        {
            shape:"rainbow-parrot-2.jfif",
            id:"v",
            class:"card"
        },
        {
            shape:"white-parrot-2.jfif",
            id:"w",
            class:"card"
        },
        {
            shape:"white-parrot-2.jfif",
            id:"x",
            class:"card"
        },
        {
            shape:"crow.jfif",
            id:"y",
            class:"card"
        },
        {
            shape:"crow.jfif",
            id:"z",
            class:"card"
        },
        {
            shape:"casuary.jfif",
            id:"aa",
            class:"card"
        },
        {
            shape:"casuary.jfif",
            id:"ab",
            class:"card"
        }
    ];
    if (current!='imposible'){
    container.innerHTML='<div>click the center of win for the next stage<button id="next" onclick="next()">next dificulty</button></div>';}
    else{container.innerHTML='';}
    container.style.backgroundImage= `url(images/win-removebg-preview.png)`;
    container.style.width='100%';
    container.style.height='100vh';
    }
    win=0;
    document.getElementById('score').innerHTML=`score:${score}`;
}
function select(id,shape){
    count++;
    com.push(shape)
    ids.push(id);
    console.log(com,ids)
    document.getElementById(id).style.backgroundImage= `url(images/${shape})`;
    document.getElementById(id).onclick='';
    if(count==2){
        displayoff(ids);
        compare(com,ids);
        com=[];
        ids=[];
    }
    
}
function compare(con,ids){
if(con[0]===con[1]&&ids[0]!=ids[1]){
    score+=10;
    for(let i = 0; i < cards.length; i++){
    if(con[0]==cards[i].shape){cards[i].button=0;
    cards[i].class='solve';}
    }
    setTimeout(display,1000)
    
}
else{
    setTimeout(display,1000)  
}}
function displayoff(ids){
    let html=``;
cards.forEach(card=>{
    if(card.id==ids[0]||card.id==ids[1]){
        html += `
        <button  class="card" id="d" style="background-image: url(images/${card.shape});"></button>
            `;
    }else{
        html += `
            <button  class=${card.class} id="${card.id}"></button>
            `;
}})
document.getElementById('stack').innerHTML=html;
}
function next(){
    if(current=='low'){
        medium();
    }else
    if(current=='medium'){
        high();
    }else
    if(current=='high'){
        impossible();
    }
    console.log(current)
}
function noback(){
    document.getElementById('stack').style.backgroundImage='';
    document.getElementById('stack').style.width='';
    document.getElementById('stack').style.height='';
    document.getElementById('c').style.opacity='0';
}